{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-graphql",
    "version": "1.0.7-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.7-TRIAL.jar",
          "url": "specmatic-graphql-1.0.7-TRIAL.jar",
          "size": 311589,
          "sha512": "3893ada92c040ab892e6beab7ed6584ac1ba7f93da174457ee9a62ed32d995343cafe1bf857c2807a4034669378bfba06207a9389e28d47e013e31c02145d58a",
          "sha256": "4a0584c9bd617f74e64d385e73c677c71f6c50d2ee8f1096d1129488ec72cc02",
          "sha1": "93953f0037eb72e0b5d6d5d14fdc04458f6a0916",
          "md5": "cec8392c324dd919c38a167b75e3d504"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.7-TRIAL.jar",
          "url": "specmatic-graphql-1.0.7-TRIAL.jar",
          "size": 311589,
          "sha512": "3893ada92c040ab892e6beab7ed6584ac1ba7f93da174457ee9a62ed32d995343cafe1bf857c2807a4034669378bfba06207a9389e28d47e013e31c02145d58a",
          "sha256": "4a0584c9bd617f74e64d385e73c677c71f6c50d2ee8f1096d1129488ec72cc02",
          "sha1": "93953f0037eb72e0b5d6d5d14fdc04458f6a0916",
          "md5": "cec8392c324dd919c38a167b75e3d504"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.7-TRIAL-all.jar",
          "url": "specmatic-graphql-1.0.7-TRIAL-all.jar",
          "size": 74108456,
          "sha512": "defaa32fa87d86bae6eb0462d873689fae3235f8ca5da84b9cc2c7e4832090138c468aa65bbe9a0c302339f991a56f783c9aed64030d8bdd7a48d565a1ece32b",
          "sha256": "f5890d44babcc2d95512b8781cb34366c8619e148bc267f7026d07ba9d3385b4",
          "sha1": "74486f4996cf7384a88bd3b20d070ca3c7b90404",
          "md5": "9397fc6343187293da73d1eb39aa9266"
        }
      ]
    }
  ]
}
