{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-graphql",
    "version": "1.0.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.3-TRIAL.jar",
          "url": "specmatic-graphql-1.0.3-TRIAL.jar",
          "size": 280553,
          "sha512": "5f8d9609189a55444f1f7fd58b4bf8274048b0026040d1642eb4f8cc41f14488864a472710c7e853317f7e19ede25e9dcbb33ffba4308abfd4850a8183965dc6",
          "sha256": "e317c68199bcd9ffd0dfcf0f122e1c37642df16373e264c637f8c85d46971033",
          "sha1": "7b8f5d4ad075c9f313efc608720eae2dbd9b332d",
          "md5": "0a83726463610e3915e6330989e738d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.14"
          }
        },
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.14"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.3-TRIAL.jar",
          "url": "specmatic-graphql-1.0.3-TRIAL.jar",
          "size": 280553,
          "sha512": "5f8d9609189a55444f1f7fd58b4bf8274048b0026040d1642eb4f8cc41f14488864a472710c7e853317f7e19ede25e9dcbb33ffba4308abfd4850a8183965dc6",
          "sha256": "e317c68199bcd9ffd0dfcf0f122e1c37642df16373e264c637f8c85d46971033",
          "sha1": "7b8f5d4ad075c9f313efc608720eae2dbd9b332d",
          "md5": "0a83726463610e3915e6330989e738d6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.3-TRIAL-all.jar",
          "url": "specmatic-graphql-1.0.3-TRIAL-all.jar",
          "size": 73144172,
          "sha512": "91042a02556dafee647a31a2d215ee1022a9c1f7f38c154945fbd75a3545c348b93993ea75aa0fbc0a6ffcf21f1f6279860ae285737882bfe86f63a51c61cd59",
          "sha256": "bf998962f37e717058b0b4fed675b44af2d42b066af87cc61427eaf618015d3f",
          "sha1": "ce44b585f7e650d11e5bfbd7655039766b0284e4",
          "md5": "590d4e922ae03f6fcd2c7eea75475877"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.3-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-1.0.3-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "fb82def22104fe53aa2bfb0ed0514890a0a91dab94169d0e14491a420a4dc47e56afa5c629d9efc5b1e6153984e409be27103371ec533bdd8a4474123488cfc4",
          "sha256": "2f29656280b5039eafe4693727c72e3273b8071799bab8f46068d8c993601c10",
          "sha1": "ab36088eac6194620258b1eec5f3e9edec33074f",
          "md5": "2e777ca06afb994c0cf29cf822cf3475"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.3-TRIAL-sources.jar",
          "url": "specmatic-graphql-1.0.3-TRIAL-sources.jar",
          "size": 41375,
          "sha512": "a1281215a05b805339f95f341f47d81fe0ebaa029322b1fb68c7d3fd3a18364daa701b819e355192da050ec94ac5dae4def80a95e9cb93edbf609c6dfb7c3e15",
          "sha256": "6795c1b4a561caeca56a585de88ef9ce3c51d36d84792d078b35e1ee82970f11",
          "sha1": "3f3ddc341ae5885550a832c9ddee0382baf74786",
          "md5": "68b860d6d7b34af0693fa279ba866868"
        }
      ]
    }
  ]
}
