{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-graphql",
    "version": "0.0.6-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.6-TRIAL.jar",
          "url": "specmatic-graphql-0.0.6-TRIAL.jar",
          "size": 227106,
          "sha512": "8ad0ec96e0b7e66f012b9094c88ef1c3149b73444237815bea064dd195d9af0be3efd5b115c272be52496e254a18a05ced3ce4d33dde3b537dae64538ace7ff5",
          "sha256": "7201f00e13307fe891fed3b7e75e84af587f6284b1d051244417a4c256ee8240",
          "sha1": "bba86fb3206212c7d30c7c696ccacdcc51c152b9",
          "md5": "a9db7fb1cd7dc44247cc442ea17eece3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.36"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.6-TRIAL.jar",
          "url": "specmatic-graphql-0.0.6-TRIAL.jar",
          "size": 227106,
          "sha512": "8ad0ec96e0b7e66f012b9094c88ef1c3149b73444237815bea064dd195d9af0be3efd5b115c272be52496e254a18a05ced3ce4d33dde3b537dae64538ace7ff5",
          "sha256": "7201f00e13307fe891fed3b7e75e84af587f6284b1d051244417a4c256ee8240",
          "sha1": "bba86fb3206212c7d30c7c696ccacdcc51c152b9",
          "md5": "a9db7fb1cd7dc44247cc442ea17eece3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.6-TRIAL-all.jar",
          "url": "specmatic-graphql-0.0.6-TRIAL-all.jar",
          "size": 53909370,
          "sha512": "e4302eb0b6adf322140b0153d9787b6bb5c3e7ce26ee4df2c7985ff65f52955afdf2ed423eaea27fbb7fd3cc28a85275545ff1922573bfed04a69fece7f9e5ba",
          "sha256": "ed55d691089bebb8a291d7a8c7392e807ca82ad86199aa90dc2d3683a2043c44",
          "sha1": "b228ac728674c2bbe20ac1b6097ec5d4787bcea5",
          "md5": "d808fddc11c6718999465d47ef4f69ba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.6-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-0.0.6-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "5a1bbfe328267d11ea12dd144922f95e93f1c031829932d1f1f3f3b7a52a2e4676d2f30d04532b11291eecd2e5ae2715a04f7de7a12a873c178ffbc4e2f605dd",
          "sha256": "db768717197ee23c50fc37e1a40c32a45f55ad3203f6fbe29baaba088b85e31e",
          "sha1": "9df432d55e2f9928a50b504a2fa8854d1c438d5f",
          "md5": "d4f783be8a3c81e7f89ad7a4fb1cefd2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.6-TRIAL-sources.jar",
          "url": "specmatic-graphql-0.0.6-TRIAL-sources.jar",
          "size": 38525,
          "sha512": "c2598f107668868ad0fa9dfff2f315e34ddf89a5d53ebcac82a5cc0cb2dc2dee4c93f327372ac16a648b631b32d548ab6eee1fd6721ba5ea2bc74990e4fbf006",
          "sha256": "c9a11c267c6ee21dcbdc0ab1ad6e96d230550f92e690841e1d2af221a09b6f82",
          "sha1": "31cf686c208cc67f5e79a44ea76140591bf01f9d",
          "md5": "6592a0096940905912b476dd875ad551"
        }
      ]
    }
  ]
}
