{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-graphql",
    "version": "0.0.1-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.1-TRIAL.jar",
          "url": "specmatic-graphql-0.0.1-TRIAL.jar",
          "size": 149908,
          "sha512": "b823b61d4f0b8499a0c341617a0e48dd1eb523b1e8df6a0fc59f8d901aafe4bff725f0dcbeb0b695c81077172b3fc5f7657fe3f5d37d1d816b5aefdb9289894f",
          "sha256": "ad1b5c72b2abf23ecbb53973f16fc16c58365115a89a215a0cac5e96e2d63c96",
          "sha1": "87a68cf7f53be5f946bf1f066ddffc96b13694b2",
          "md5": "5516bfc7e1bd3619824ed281a6470689"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.20"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.1-TRIAL.jar",
          "url": "specmatic-graphql-0.0.1-TRIAL.jar",
          "size": 149908,
          "sha512": "b823b61d4f0b8499a0c341617a0e48dd1eb523b1e8df6a0fc59f8d901aafe4bff725f0dcbeb0b695c81077172b3fc5f7657fe3f5d37d1d816b5aefdb9289894f",
          "sha256": "ad1b5c72b2abf23ecbb53973f16fc16c58365115a89a215a0cac5e96e2d63c96",
          "sha1": "87a68cf7f53be5f946bf1f066ddffc96b13694b2",
          "md5": "5516bfc7e1bd3619824ed281a6470689"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.1-TRIAL-all.jar",
          "url": "specmatic-graphql-0.0.1-TRIAL-all.jar",
          "size": 53650702,
          "sha512": "c2db12d95510309d15e57855d60ee5fc94064288e52f74db1d5f36f19b83a9366130349ae89782e38abfeabeb8f39885a453e674e099029d1faf1c30ef5c5bb7",
          "sha256": "1d47ea1c235c4583d59e8dc9ff85fb42bce35b7cb961d64f0a80cf7e0cf344d8",
          "sha1": "bb57ab8eda6f256e6eb6867401adb888d3036534",
          "md5": "291bd66204d6a29ee56cfd19749979ed"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.1-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-0.0.1-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "4f5405472d6b47f17703f1558e381958afc0582fd515b2789f7d2f4033b839af79eb29c6f5fc39a6392dd850843341328130abd9f97c4536975521e4497c65ea",
          "sha256": "a28867b6184a7a6c04743a1c191d138eb4a61fd4827f43e73c48508b540ab6dd",
          "sha1": "4cb0f8f80135a0b17c81359522756ca2cc5a267f",
          "md5": "16b6fcddff9bc7838b2aac9bcd775fb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.1-TRIAL-sources.jar",
          "url": "specmatic-graphql-0.0.1-TRIAL-sources.jar",
          "size": 25201,
          "sha512": "b1af14383c348978f7e534cfe2f69a5e64d9722100c8c58cf90f8dcc5c1b05d33aae753e6032a98328cc2e30c7cf2fed85849f32fefc6795ba452d93533fb192",
          "sha256": "509c8e9be558ec9d179924309631d8e8c4b69c6a21a259af8c6110ffe2e6ddf9",
          "sha1": "448369d7b6bdf5ea99dbca913b57c1911ba1a7cc",
          "md5": "3a4e99a94b4e27eedc3c42370fb778ac"
        }
      ]
    }
  ]
}
