{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-graphql",
    "version": "0.0.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL.jar",
          "size": 190159,
          "sha512": "a4409b9d5702d61db83c9933f37cc7172c09370b4d2066cb2a6a3edc5f4d88fc0030f3b2cea4cc562139f57c90c5886fbb0c7fe35a5c64811392ecd507fd2b1f",
          "sha256": "b83e38b6eb993aa077e3ad47289ee4c76fa0b35a9261086a3f4fcf5bd4b48213",
          "sha1": "72d46fc4264edefbbcca0dd55ad3ba64502a6014",
          "md5": "507128fe61caa2f5e607a8b1593af1d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.32"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL.jar",
          "size": 190159,
          "sha512": "a4409b9d5702d61db83c9933f37cc7172c09370b4d2066cb2a6a3edc5f4d88fc0030f3b2cea4cc562139f57c90c5886fbb0c7fe35a5c64811392ecd507fd2b1f",
          "sha256": "b83e38b6eb993aa077e3ad47289ee4c76fa0b35a9261086a3f4fcf5bd4b48213",
          "sha1": "72d46fc4264edefbbcca0dd55ad3ba64502a6014",
          "md5": "507128fe61caa2f5e607a8b1593af1d4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-all.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-all.jar",
          "size": 53859263,
          "sha512": "1c43b14eefa23bd5751f0d459d852ae284a5b4aa5f75448f0b7a967a5be523ab089d44506acc5a24eede84d5f4f5ae84c59a99c3c7eefd40d3362df7aa6ea505",
          "sha256": "122cb4652607fd08e1266d1f62bf1664f5a0e4f49c24032edd446bebb52d12b9",
          "sha1": "af156e657a17ccdc45fb704e8b36dff3518c23f4",
          "md5": "577c07404cd20fb28549d26c879fb775"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "17bf4bf1a2f8dddc5041c0c8a4c0019e678971fe3a9c522df923f227ec19660ed3a1d25c0639ca7436de2f1bb3c0ce10c8feff88aaf1e3dc4f8a93b95e50ba14",
          "sha256": "f58704d80d29c4f29064019658e1e1898ba4d0af779e391df174b3837f7de07f",
          "sha1": "b2566e4947179943d055c67a1bc4039e25a55e1b",
          "md5": "15b6e30057b2b4964a27e0f86ee4d53c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-sources.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-sources.jar",
          "size": 32890,
          "sha512": "9d4fa110780df32b0210ced4e7b31591bbb73c811eb708b7971d4a7c029a056d71268e4a29c9351e32e0dc79112099a4b965b3c8b7ea1c8723560c7e6d807efa",
          "sha256": "5a68bbe356953ce0b1ef6fe1279ccd14625632fabe4d7fa6364689885fbc8142",
          "sha1": "184117472a0e24f29a34da8edd3c8f9a73d2c862",
          "md5": "22c04492b208312936ec42401bb4adc7"
        }
      ]
    }
  ]
}
