{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-graphql",
    "version": "1.0.0-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.0-TRIAL.jar",
          "url": "specmatic-graphql-1.0.0-TRIAL.jar",
          "size": 269858,
          "sha512": "ba2d8dee852285744a0efd10d48c5ee870c85331d1e9592427760276358b688fe26b92aaf309871e861540e30a7414269d46dde0790d3db5bf5f47bb5121e18e",
          "sha256": "6f12505d14b5adc09f14f3088f7346a14d2509aa1da85cdacb824c1e3f7c0dbf",
          "sha1": "f2128d03403b252b6915e9c44feca5a009ed1756",
          "md5": "b7d6724092d3771575ee3f55dacd70df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.0-TRIAL.jar",
          "url": "specmatic-graphql-1.0.0-TRIAL.jar",
          "size": 269858,
          "sha512": "ba2d8dee852285744a0efd10d48c5ee870c85331d1e9592427760276358b688fe26b92aaf309871e861540e30a7414269d46dde0790d3db5bf5f47bb5121e18e",
          "sha256": "6f12505d14b5adc09f14f3088f7346a14d2509aa1da85cdacb824c1e3f7c0dbf",
          "sha1": "f2128d03403b252b6915e9c44feca5a009ed1756",
          "md5": "b7d6724092d3771575ee3f55dacd70df"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.0-TRIAL-all.jar",
          "url": "specmatic-graphql-1.0.0-TRIAL-all.jar",
          "size": 54332839,
          "sha512": "ccbfa3afac12791a80614900a9a50e7d1f59d2e0eddd3a97d573cccbb6d8fdc62eda85202101db4fabbc21c469ebdfbf6372dbadb92ca4e8625edd5622d015cb",
          "sha256": "84945f119bc92516837e43958915b7c562e1235bd4ae412cd45ebb2986bb870e",
          "sha1": "813f2fc12a02baf07ac0a4491e1151311c0ef93a",
          "md5": "2347ddb97b4338bc68e833839a55a508"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.0-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-1.0.0-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "cfcb58c0f87aed912d45aa59d35c6e05717cf5d950485f30023e15d720677bb2a9659cc728d1a375b400ecdffc7cfbc2159fb6434f69d42bb9efb482d35b5510",
          "sha256": "4ffbfecc35585a57b71de5ee4aca1c896ae9971ebec2d375d0632cbac6e254ed",
          "sha1": "9e836891f3547fe252ab37c74bc14df3a4ec7c03",
          "md5": "31e730468dc7a3777b75423bb77a0356"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.0-TRIAL-sources.jar",
          "url": "specmatic-graphql-1.0.0-TRIAL-sources.jar",
          "size": 39381,
          "sha512": "cd46b926e929a28846396a3ef66e174d032ebf68f51794f5ec80068afea5eed6902e1a47e92906120150f09442acee66c4ddd8320acc21e825fe3d122d772b4a",
          "sha256": "b4bc310b5fbe40b334eddc4e4307314564c8017ca9f56f43237d49b1c0a0d346",
          "sha1": "fb24b8754804bf5c04b4606573a8d2ea6633bdcc",
          "md5": "3cd835cd276115a2c75d792cd2df8a7b"
        }
      ]
    }
  ]
}
