{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-graphql",
    "version": "0.0.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL.jar",
          "size": 191842,
          "sha512": "bcc7976cac0d7b890fab82fe3d7b9a275a808b98b21760ffecf03ab5dfc90ad51f3d2c3ecd52fe3128d59bb453c626ee31b85bd279362d39c46f123c7c4a724c",
          "sha256": "6a0fdf8ffd4d852f2f0e164559a25fc919d3cb6b0c39b31240730291f3ea12d4",
          "sha1": "9ee946c634f0d771ca1a354d280948a175265ee5",
          "md5": "d0add0343cd6051133233a9c5ab9bee7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.33"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL.jar",
          "size": 191842,
          "sha512": "bcc7976cac0d7b890fab82fe3d7b9a275a808b98b21760ffecf03ab5dfc90ad51f3d2c3ecd52fe3128d59bb453c626ee31b85bd279362d39c46f123c7c4a724c",
          "sha256": "6a0fdf8ffd4d852f2f0e164559a25fc919d3cb6b0c39b31240730291f3ea12d4",
          "sha1": "9ee946c634f0d771ca1a354d280948a175265ee5",
          "md5": "d0add0343cd6051133233a9c5ab9bee7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-all.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-all.jar",
          "size": 53860327,
          "sha512": "102c8c99088b895e6992da0476a78c1cec0fbe2f8f12ae37f2d0b6ee4bdf7369b14c41c284e8462157c7f74d42038c1ec4bd75aebcc448db009bce736bd0b4e6",
          "sha256": "496fd7d8e33a601890e90c3e7f3b68ceb1228f9f727850e395914020f455fa1f",
          "sha1": "d6dc435af2cbe0589d54befc506b758cd5916f09",
          "md5": "f64223679a8150c264f2bec51cdc1f45"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "6ddfd8b7ecec79fa52442b18b0ec59a061931af17177aa5cbb46be91db241c71abe2fc0dd78f0122ddfaee895a06e87d0b04bb27062a2d96e29ca9fd349b5342",
          "sha256": "973bb86793503be064d7c7a208aa17f4ad810fd1914c1ae47c3e86c03be82c2f",
          "sha1": "0dac41962d2f636f2cbb6c3ce59f2f36b254fc34",
          "md5": "d0480495a6bc6bb6201c4e6e7ae2fd5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-sources.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-sources.jar",
          "size": 33227,
          "sha512": "0f6a727b1c23e4766aedb57419395d5561a7e03a986c381f3ee92c46d7a5c3a3b49f73da819025dc46a192a92e947a834abe1a78009468457ed02da5e21e39cc",
          "sha256": "96586de651a05c4702915f4a33c1e2d07b005341eeb6d7dafca9ec463e369a18",
          "sha1": "5fdbf626a31225473284cc0b8ce33fc476818955",
          "md5": "ac8f60cfd93490193c5138dfc7ef50d1"
        }
      ]
    }
  ]
}
