{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-graphql",
    "version": "0.0.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL.jar",
          "size": 194395,
          "sha512": "52960a167f37fc443ed6a5c6c68f1c8cbbd016cb99e5638e0306144cf116ad24bd8dd638da975cb27b6da1d213683dd8d96a5a4bb4b71e51bd1743127726dff3",
          "sha256": "0ffb43e746ef4776aa1b9225016f35230ce577fdc5d05c551073b9826a462d7e",
          "sha1": "ca51628139d1ba849fc0a835984ade9b8253c209",
          "md5": "d8721671111079c533d3363687da7e4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.33"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL.jar",
          "size": 194395,
          "sha512": "52960a167f37fc443ed6a5c6c68f1c8cbbd016cb99e5638e0306144cf116ad24bd8dd638da975cb27b6da1d213683dd8d96a5a4bb4b71e51bd1743127726dff3",
          "sha256": "0ffb43e746ef4776aa1b9225016f35230ce577fdc5d05c551073b9826a462d7e",
          "sha1": "ca51628139d1ba849fc0a835984ade9b8253c209",
          "md5": "d8721671111079c533d3363687da7e4a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-all.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-all.jar",
          "size": 53863349,
          "sha512": "497c73b9cd335f94ba37d83906698533ae04acf7c41b15ea5df015c1ba919b2c511d7776110e6f5d4a5084555a796e99ccad1a47c34be33fae4017c28c6e47ce",
          "sha256": "cc6ef69c7227e96f70ef7890d945906da7256b0cf00ce21dd1027eb559c73bff",
          "sha1": "eb2146af6a74489b6229421850a6be905766b528",
          "md5": "4f6f5731b7507123340412bb04aa06b2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "be133b5bcfdac66ae955cad108e66568fe57095e89ae849a9c716fdc5cdf690c2e82a93449e81eb52a0150f6d017feec729f74f64bdd9ce760ba8727c7fc8d3b",
          "sha256": "0ed4ac702fe2808bfa98f14845b2b128dca8b044ea162ecc6130fd01128e3d40",
          "sha1": "aa69794220676fb49da8e6a525252b2a736289b3",
          "md5": "c60dcd09f790a4f3da879b3304dac34d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-sources.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-sources.jar",
          "size": 33904,
          "sha512": "451bb17e0d75b56b724507a394ccda519d5abd4f0954b8dc5589e3ec523370efb4bcc7d86a6cc3b13b361485c9443af0b21426fec1ee5944c8e944d279813a9e",
          "sha256": "023d56fc4159cd46d7a4cf3129f7db7b6a2f039b86895fa42aaa77ebc625f57a",
          "sha1": "7caf3ad1ee4eb32b052aa344662407b3aa038f83",
          "md5": "59fdcadb8a85aacb927b32be996b5031"
        }
      ]
    }
  ]
}
