{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-graphql",
    "version": "0.0.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL.jar",
          "size": 193009,
          "sha512": "0ae18aa07110b65e08593d6c86d335bdca6048a33ad6ec92ce409c7ec9b5003988454b9a0da5d8db2f17879be57cd73ba55d22f6d8b61558a2e2fa7e212d3600",
          "sha256": "e3e404535c5da9c93ea2889d6997dee629c16130ef2d59f2bf0d51b5b6f968b6",
          "sha1": "750818bbe472bcecdfbed2222d0f7e4429b0cdd6",
          "md5": "09c7402c6a3589260104aef44558f8a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.33"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL.jar",
          "size": 193009,
          "sha512": "0ae18aa07110b65e08593d6c86d335bdca6048a33ad6ec92ce409c7ec9b5003988454b9a0da5d8db2f17879be57cd73ba55d22f6d8b61558a2e2fa7e212d3600",
          "sha256": "e3e404535c5da9c93ea2889d6997dee629c16130ef2d59f2bf0d51b5b6f968b6",
          "sha1": "750818bbe472bcecdfbed2222d0f7e4429b0cdd6",
          "md5": "09c7402c6a3589260104aef44558f8a8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-all.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-all.jar",
          "size": 53861769,
          "sha512": "26bafc4bb81e23b21463e24fc0e79d88ef92edf89250fa69fbf79a43c37a1e83e9469aeb6314ba7b7014e1232f8bdc77914227651702bf82ee8848fd690be18b",
          "sha256": "5bafce3c88181648ed944d138463b63373e2839ef84cd62a32c0cd063684274c",
          "sha1": "0b812aa3a492e2965d623e31e96c0c55e877eb0c",
          "md5": "e71e9b71125afa21a6e5be06ac800298"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "6a52c1081e4973652ef495c2163075aedefa199d08f1411203fc27169a1dfee91df8caae03493ad9d939927467fc192570237389f4a07edce62bc5c879a1bf63",
          "sha256": "d0e8e5ffc5a4d565dbcbc9263d8b5c24a5da0edc35835eab7b12c20a246ec99a",
          "sha1": "8891ef237e30d57b6fa42f3bd9546fb217c40dcd",
          "md5": "aca5bfc2b29e04b2a1669e151de6351b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.3-TRIAL-sources.jar",
          "url": "specmatic-graphql-0.0.3-TRIAL-sources.jar",
          "size": 33581,
          "sha512": "adfc94cb62bc46a3b04487f6099864f4c5f4aa26e2d183e5efe2cc9bc7e9cd2d99eee2a0063c27e38a09a635fec28dd126ec463f9f9faeeddda5122db669c12d",
          "sha256": "a8563d5e2586254cea1e79344a84dcda98f1249ff2c096f6017d2c1c39f31fd1",
          "sha1": "6bb58abba754a9921a46f318448147d86d1e9c11",
          "md5": "18a16aac9fcdd1804016979155c53781"
        }
      ]
    }
  ]
}
