{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-graphql",
    "version": "1.0.2-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.2-TRIAL.jar",
          "url": "specmatic-graphql-1.0.2-TRIAL.jar",
          "size": 239985,
          "sha512": "075926ca4f0bfc5ebbcb02e4e56ce3312257e610d57a612025bc211918f0c981ac8bfa20b2c21f093b4a5b80dc89e77f2468e1b2f3a4a854938731e32f972ae8",
          "sha256": "7076042e1b77beac6389852d3b141bce0c799faedffe82ce5df04cbea6d1de9c",
          "sha1": "a3e83da4b509c77466a6834a157deea1db2dd404",
          "md5": "1f4abbd374a0c7e15773fc09c53397c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.14"
          }
        },
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.14"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.2-TRIAL.jar",
          "url": "specmatic-graphql-1.0.2-TRIAL.jar",
          "size": 239985,
          "sha512": "075926ca4f0bfc5ebbcb02e4e56ce3312257e610d57a612025bc211918f0c981ac8bfa20b2c21f093b4a5b80dc89e77f2468e1b2f3a4a854938731e32f972ae8",
          "sha256": "7076042e1b77beac6389852d3b141bce0c799faedffe82ce5df04cbea6d1de9c",
          "sha1": "a3e83da4b509c77466a6834a157deea1db2dd404",
          "md5": "1f4abbd374a0c7e15773fc09c53397c8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.2-TRIAL-all.jar",
          "url": "specmatic-graphql-1.0.2-TRIAL-all.jar",
          "size": 73144114,
          "sha512": "bcd6db9256a138d7196c18f77f8c88e1968594622195f94f843f6792060091d60d8a7348b8817eeb63db5c8ba755dd383d00ff5bf3e31ff485b8bd7ff2bc1c34",
          "sha256": "1c6a5bef2106600b3e905cce2f0182f794cf8098b89e042f929985fc57bae638",
          "sha1": "9d9e62d3b034fafbde21289f5c32118a7ce666c0",
          "md5": "37e5f4079ffbf2a7f719474950026be3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.2-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-1.0.2-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "0f1b82989c911ed8f6cc96172ebdc7b19838b616e68e769a7d415147f70f46e5d31a15b2d6fb473e8f5e7d5fd821bf92c836098777ae1e29e4a9a5d6274d6b5b",
          "sha256": "91a318ab3e5e5459a5c10291852e53fb96aaa7591d73d182d3cf80e0bb786f23",
          "sha1": "b6ecef094f438a364fb5d45cf431a435a77ace6f",
          "md5": "6d8962592c40bcce2817dbcfe9915757"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.2-TRIAL-sources.jar",
          "url": "specmatic-graphql-1.0.2-TRIAL-sources.jar",
          "size": 41342,
          "sha512": "dc3ae1f1649b4b7621ea3e954151e2be5a247b9c9b6c60c4140426151b8a9c74cc6b00aee2593867b3e43b1c33546f00960e04d51435357e8ee8a4d1ce49a21f",
          "sha256": "c96fc3db3a88b9c1b9ef5189ddf760e41cd0f97c12d3c0a9dde9425850e4360a",
          "sha1": "a9860e4fd4afdd08473bc1466efb5d11212d769b",
          "md5": "3a8efa6f871dfbb0b27ef711b7e23f28"
        }
      ]
    }
  ]
}
