{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-graphql",
    "version": "0.0.7-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL.jar",
          "size": 266907,
          "sha512": "ede702429d77afc4c4b62f4f067cb48b5aaebda0b28b4599ed3e73005cdca7a71790eef505824074dc4df6ec83719afe0df9cae0b74bb0eda2c1d4b62a026c69",
          "sha256": "59c27bb5686c0f76485a8e341ae0096e68874fed59700b44fb1ccb60c5c5f251",
          "sha1": "60009056f39690dfeb168cae5d55c26c4101e891",
          "md5": "ac18a6833067ad581c19f78bdb7307f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL.jar",
          "size": 266907,
          "sha512": "ede702429d77afc4c4b62f4f067cb48b5aaebda0b28b4599ed3e73005cdca7a71790eef505824074dc4df6ec83719afe0df9cae0b74bb0eda2c1d4b62a026c69",
          "sha256": "59c27bb5686c0f76485a8e341ae0096e68874fed59700b44fb1ccb60c5c5f251",
          "sha1": "60009056f39690dfeb168cae5d55c26c4101e891",
          "md5": "ac18a6833067ad581c19f78bdb7307f2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL-all.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL-all.jar",
          "size": 53961968,
          "sha512": "cc15160a91b885d2b8f1cc39c350ec28fe2848021dfe04bdd0909b583f9aac49935f5e2931f130bea279073643df1d3b39b95f6694fb7af55684574ecd4afebd",
          "sha256": "a736342171b342d4544c094afde94ada09e814e5f7b64d5485ebf5d5d61f524a",
          "sha1": "8fd863537e5e05b60e2f76c39ce21d44c03c321b",
          "md5": "2c6d20f0b7b4ada01aedb01d4389b14f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "c28c324e9652d71c275eed889cb12703c7949419be5c4c633622128c36a5bd45a216d190eb6a5781d0d4234bfdbf8a599fbb0ba49ad09b8d6d8454dbacc7aba0",
          "sha256": "c24701a21c7a12785bea8c8f4e0c875df2b7203c107a5655a3f69fc09cfeb375",
          "sha1": "255c34a5be1f012d5fa22dfa688c3071ba132db6",
          "md5": "a01f0d3470622c23a3669bead41eeeed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL-sources.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL-sources.jar",
          "size": 38836,
          "sha512": "8c0223103a7725209e9862a6711a2365c79648a7f9896d3bd6a225047c0eb492b813609ef3423e15b3bd4665a71e52f5709414ad50bbe2b4acec4e1bbd7a9d6a",
          "sha256": "345da2cc93a46ad93e8385b9c98b03ad69f2d145715a3296f119b07d80c47abe",
          "sha1": "c5ab1d54201641ce56bb4a25342340eae3772471",
          "md5": "33158fa2879e5f07a99cf731a688b6b3"
        }
      ]
    }
  ]
}
