{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-graphql",
    "version": "0.0.7-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL.jar",
          "size": 228093,
          "sha512": "f5da72d7f9d18e28d570f373f8398ab83f001d4da346f0607c8d5737ed9cfd23f1715a162007e049ed5a30f299ea816bef8ed27c5f9726a5169e567eaff7ffe1",
          "sha256": "2925f8feead624d217fce1aeb74292a95a6617aa020a859ca9c3ab0d6f704347",
          "sha1": "e39be95dfa26b58516f138a0189d3b93f97eea3c",
          "md5": "7521b726b9c8801ad639749040f14a7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL.jar",
          "size": 228093,
          "sha512": "f5da72d7f9d18e28d570f373f8398ab83f001d4da346f0607c8d5737ed9cfd23f1715a162007e049ed5a30f299ea816bef8ed27c5f9726a5169e567eaff7ffe1",
          "sha256": "2925f8feead624d217fce1aeb74292a95a6617aa020a859ca9c3ab0d6f704347",
          "sha1": "e39be95dfa26b58516f138a0189d3b93f97eea3c",
          "md5": "7521b726b9c8801ad639749040f14a7f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL-all.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL-all.jar",
          "size": 53961481,
          "sha512": "59974c5d980864a29e9711fddce7b2ca7a5f006548390f37fb0592ea8ce20488f3ef3677637c9257aef186c0290903bf553fe0f43cd13dc3b8b7be31b3e0c2a5",
          "sha256": "657aa95107fb18b6ad25050ad37a852631f9501fb9b93c8d40aa7f43edd42c51",
          "sha1": "c70e0426dbd2dd418673531a5b41957d6d4f83ef",
          "md5": "f59b66ebf8c334352204892f9fbcab67"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "30f313297fefbbea78e1619ad701f99d261f23a43c2725e63bf68408f7818159c24f1d2a338dc7e739313f6c12798686fdaace981702b0663d5814c957acd8f0",
          "sha256": "1ac03cc59c0651c9e4d15e37e51e4abdee7cb952b55318ceb28582958df40cde",
          "sha1": "d4952df886a5b19da29031e333497dae52672ec4",
          "md5": "4a0002af33780b450eb24ec69ff251d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-0.0.7-TRIAL-sources.jar",
          "url": "specmatic-graphql-0.0.7-TRIAL-sources.jar",
          "size": 38652,
          "sha512": "6ab9d0ba2dfc379e5c6f0cde6c3783a8856fea4bbae810a49e91fbda8c1aecb04d7ddb36589781377a3b6786115411460c042f92886b3415406c9cc1dd9f0515",
          "sha256": "72afeb366530ed7cca239bb8872cad494de3a0bd203126a444a0587f71cca43a",
          "sha1": "8815b6fa9a5b27fadb92c2b4468305bd4ff3308c",
          "md5": "a6a22ca3c9c3abaa38dfcda1aaeb1a0b"
        }
      ]
    }
  ]
}
