{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-graphql",
    "version": "1.0.5-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.5-TRIAL.jar",
          "url": "specmatic-graphql-1.0.5-TRIAL.jar",
          "size": 260976,
          "sha512": "eb12423d6bea20a82fd1aff8e7221ff325fd903baf06c9d172b4a5e0be314f1534dcbbcec179831ce232bc52dfcf38020999ea4647aaeb8f5ade514b5eadd7a9",
          "sha256": "647d460d20c9e75c392ec52a01dc890f7d790617e140b462b43992f83d8ddf9a",
          "sha1": "e9efb5ca45f8dde775034f301da8c366bcb34beb",
          "md5": "9b00fa9df0e2a7a31f90558273c7a019"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio-jvm",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-graphql-1.0.5-TRIAL.jar",
          "url": "specmatic-graphql-1.0.5-TRIAL.jar",
          "size": 260976,
          "sha512": "eb12423d6bea20a82fd1aff8e7221ff325fd903baf06c9d172b4a5e0be314f1534dcbbcec179831ce232bc52dfcf38020999ea4647aaeb8f5ade514b5eadd7a9",
          "sha256": "647d460d20c9e75c392ec52a01dc890f7d790617e140b462b43992f83d8ddf9a",
          "sha1": "e9efb5ca45f8dde775034f301da8c366bcb34beb",
          "md5": "9b00fa9df0e2a7a31f90558273c7a019"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.5-TRIAL-all.jar",
          "url": "specmatic-graphql-1.0.5-TRIAL-all.jar",
          "size": 73217972,
          "sha512": "45554cf209c4463080ee11f820a5cdaf0064c4d719abdde142274132a13cf1ed39059509b79381c747b75075a779baf01faafb748344a20a76835af5688a0830",
          "sha256": "f24901128353c87cce8cf265c08b49d318ba21ca085204245629e15b1bc12624",
          "sha1": "4a80ceca9f573f39f7c38039a9b560599a85371a",
          "md5": "756cf5b9c66212d1f4593e48f5e0ba2a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.5-TRIAL-javadoc.jar",
          "url": "specmatic-graphql-1.0.5-TRIAL-javadoc.jar",
          "size": 261,
          "sha512": "2737a9180fe98ead6de921a87837995e9a22b6dbc5769a7f71a2544f8d99cff522d0e2610dcbdc095c1265e7d807443d81b168990679623bd7f427229d81dd98",
          "sha256": "db65da1b66bfa2372bbfe4ac1d718a83401a5731388134cc1c7cb318b992bcc3",
          "sha1": "3a0dc59239f545ea918f1d27377e79bcb3cf07bf",
          "md5": "06a7b5801d82670220584137bc703748"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-graphql-1.0.5-TRIAL-sources.jar",
          "url": "specmatic-graphql-1.0.5-TRIAL-sources.jar",
          "size": 43617,
          "sha512": "282524bc1009a86d7b5d80008a158a2e179c4fee87e9f64c1a8cac88a2949004ad20382d07d80a95704a73682e278c1f51071bf29fda493357887ff56b2902ca",
          "sha256": "bac2b915375b7a1ed22c707ae2b568619e6d822883671252339bc000930dbd31",
          "sha1": "aceb92535959b8ee70d33ca50b340b7b9eb2b398",
          "md5": "f4e05a077f0cb8a09cc39ed6cba8d181"
        }
      ]
    }
  ]
}
